title: Process Created via WMI
id: h1234567-wmi-exec-detect-001
status: production
level: high
logsource:
    category: process_creation
    product: windows
detection:
    selection:
        ParentImage|endswith: '\WmiPrvSE.exe'
    filter:
        Image|endswith: '\WmiPrvSE.exe'
    condition: selection and not filter
tags:
    - attack.execution
    - attack.t1047