title: Remote System Discovery Commands
id: 08901234-1234-89ab-cdef-12348901234a
status: production
level: medium
logsource:
    product: windows
    category: process_creation
detection:
    selection_net:
        Image|endswith: '\net.exe'
        CommandLine|contains:
            - ' view'
            - ' group '
    selection_nltest:
        Image|endswith: '\nltest.exe'
        CommandLine|contains: '/dclist'
    selection_powershell:
        CommandLine|contains: 'Get-ADComputer'
    condition: selection_net or selection_nltest or selection_powershell
tags:
    - attack.discovery
    - attack.t1018